### PR TITLE
update notebook for up and odisha

### PR DESCRIPTION
**Pull request by apurvabisht97**

### CODE REVIEW

**Review by dileep-gadiraju — CHANGES_REQUESTED** [review]
Please don't change anything in v1.5 folder for now

**Comment by dileep-gadiraju** [comment]
Please do cellId and roiId changes to json files under data/ folder.

**Comment by dileep-gadiraju** [comment]
there are unwanted changes , so closing the PR

**Comment by apurvabisht97** [comment]
okay..

**Pull request closed without merging**
